import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Offers from './components/imageSlider/Offers';
import Header from './components/Header';
import Footer from './components/Footer';
// import Offer from './components/imageSlider/Offer';




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen '>
        <Header/>
  
        <main className='flex-grow'>{children}</main>
         <div className='pt-4'><Footer /></div>
        </div>
      </body>
    </html>
  )
}
